* Pakora :indian:snack:
:PROPERTIES:
:source-url: https://www.veganricha.com/onion-fritters-simple-pleasures/
:END:
** Ingredients
*** Vegetables
- 2 medium onions -- sliced thin
- 1 chili pepper -- chopped
- 1 bunch cilantro -- chopped
- pinch hing
- 1 tsp cumin
- 1 tsp ajwain (carom seeds)
- 3 tsp salt
*** Batter
- 3 tbsp besan
- water
** Directions
- Mix vegetables
- Add to batter
- Medium high
  - Fry spoonfuls of batter
  - Turn for even frying
- Fry chilies separately for garnish

* Toor dal :indian:
:PROPERTIES:
:time: fast
:END:
** Ingredients
*** TODO Ingredients
- Jeera seeds?
*** Dal
- 2 cups toor dal
- 8 cups water
- salt
*** Tempering
- 1/2 tsp mustard/jeera seeds
- 1 large tomato -- chopped
- large pinch hing
- 8 curry leaves
- 2 dried chilies
- 3 cloves garlic
- salt
- sugar
- cayenne pepper
** Directions
*** Dal
- Instant pot 3 minutes, 10 minute release
*** Tempering
- Oil, mustard/jeera seeds, hing
- Chilies, curry leaves
  - Stir a minute
- Garlic
  - 30 seconds
- Chili powder, tomato
- Sugar
  - Until raw tomato smell goes away
- Mix with dal
* Masoor dal tadka :indian:
:PROPERTIES:
:source-url: https://www.veganricha.com/masoor-dal-tadka-indian-red-lentil-dal/
:servings: 2
:time: long
:END:
** Ingredients
*** TODO ingredients
- Bay leaves
*** Dal
  - 1 cup masoor dal
  - 3 cups water
  - 1/2 tsp salt
*** Tempering 1
- 1 tsp oil
- 1 medium red onion -- thinly sliced
- 2 cloves garlic -- minced
- 1 tsp ginger -- minced
- 1 tsp coriander -- ground
- 1/2 tsp cumin -- ground
- 1 medium tomato -- chopped
- 1/4 tsp salt
- 1 tablespoon yogurt
*** Tempering 2
  - 2 tsp oil
  - 1/2 tsp cumin -- seeds
  - 2 bay leaves
  - 2 chilies
  - 1/2 tsp kasuri methi
  - 1 garlic clove -- julienned
  - 1/2 inch ginger -- julienned
  - 1/4 tsp paprika
  - pinch ground cloves
  - cliantro, lemon juice -- garnish
** Directions
*** Dal
- Instant pot 3 minutes, 10 minute release
*** Tempering 1
- Medium pan
  - Oil, onion, garlic, salt
  - Until onion is golden-brown
  - Take half for garnish
- Add ginger, coriander, cumin
- Add tomato, 2 tbsp water, 1/4 tsp salt
  - Until tomato is tender
  - Mash large pieces
- Add yogurt
- Mix in dal and boil
*** Tempering 2
- Oil, cumin
  - Until fragrant
- Bay leaves, chilies, kasuri methi, ginger, garlic
  - Until garlic is golden
- Paprika, cloves
  - Take off heat
- Add reserved onion
- Add to dal
- Garnish with cilantro, lemon juice
* Malai Kofta :indian:
:PROPERTIES:
:source-url: https://www.veganricha.com/vegan-malai-kofta-recipe/
:servings: 4
:time: long
:END:
** Ingredients

- 1/4   cup     ( 50   g )   shelled hemp seeds or pumpkin seeds or almond flour or chopped cashews    (cashews and almonds are the most neutral flavor)
- 1   cup     ( 210   g )   heaping cup cubed potato or 1 cup grated/shredded potato, raw   (1 medium potato)
- 2   cloves        garlic
- 15   oz     ( 430   g )    can chickpeas    or 1.5 cups cooked
- 1/2 to 3/4   tsp        salt   depends on if using salted or unsalted chickpeas, I used 3/4 tsp
- 1   tsp        garam masala
- 1/2   tsp        ground cumin   preferably roasted or use Dry toasted whole cumin seeds
- 1/4 to 1/2   tsp        cayenne/indian red chili powder
- 3   Tbsp        oat flour or regular flour   Or other flour of choice
- 1   Tbsp        cornstarch or other starch
- a generous pinch of baking soda
- 2   teaspoons        safflower or other neutral oil
- 1/2   teaspoon        cumin seeds
- 1/2   teaspoon        coriander seeds
- 1        bay leaf
- 8    cloves        garlic   coarsely chopped
- 1   cup     ( 160   g )   chopped red onion
- 1   1-inch knob         of ginger, chopped
- 1/2   teaspoon        turmeric
- 1/4 to 1/2   teaspoon        cayenne
- 1   teaspoon        Garam Masala
- 1 1/2   cups     ( 225   g )   chopped tomato   fresh or canned
- 1/4   cup     ( 30   g )   raw cashews,    See note for nut free
- 1/2 to 1   teaspoon        salt
- 1/2   cup     ( 120   ml )   water or unsweetened almond or other non dairy milk   divided
- 1 1/2   teaspoons     ( 7   g )   dried fenugreek leaves
- 1/2   teaspoon     ( 3   g )   sugar
- Cashew cream or coconut cream for garnish

** Directions

1. Kofta: Process the hemp seeds or nuts until you have a coarse meal. Add potato and process until coarse. Add the rest of the ingredients and pulse until most of the chickpeas have broken down but not a paste. (Without processor, use nut or seed flour and grated potato. Then mash chickpeas and mix)
2. The potato will leak moisture in the mixture in some seconds making it easy to make smooth balls. Do not let the mixture sit for too long at this point. Add more flour or starch if the mixture is too moist. Add a tbsp nutritional yeast for cheesier flavor profile.
3. Take 2 to 3 Tbsp of the mixture and make round or football shaped balls - 1.5 inch size or smaller so they cook through. Place on a parchment lined baking sheet. Bake at 425 F (218 C). For 20 minutes. Or pan fry in 1/2 inch oil for 5 to 6 minutes until golden on most sides.
4. Gravy: Heat the oil in a large skillet over medium heat. Add the cumin, coriander, and bay leaf. Cook for 1 minute. Add the garlic and cook until slightly golden on some edges, 2 minutes. Add the onion and ginger, and cook until golden, 7 minutes, stirring occasionally. Add the turmeric, cayenne, and garam masala, and mix for a few seconds.
5. Add the tomato, cashews, 1/4 cup water and salt and cook until the tomatoes are saucy, 5 to 6 minutes. Stir occasionally to avoid sticking. Cool slightly, then transfer to a blender.
6. Blend the mixture with 1/4 cup water, half the fenugreek leaves and sugar until smooth. Fold in the remaining fenugreek leaves.  (This sauce is incredibly versatile,  you can just add some chickpeas, baked tofu, roasted or par-cooked veggies and simmer and use!)
7. Bring the blended sauce to a boil, add baked kofta balls and serve. Garnish with some cashew cream or other on dairy cream and cilantro. Serve with  Naan  or rice.   To store: store the balls and sauce Separately until ready to serve.
