
* Pinto Bean Soup :soup:beans:
:PROPERTIES:
:source-url: https://www.budgetbytes.com/pinto-bean-soup/
:END:
** Ingredients
- 1 lb pinto beans
- 4 cloves garlic
- 2 tbsp olive oil
- 1/2 tsp chili powder
- 1/4 tsp cumin
- 1/4 tsp oregano
- 1/8 tsp cayenne
- 2 cups vegetable broth

*** TODO groceries
- pinto beans
- better than bouillon
** Directions
*** Beans
- Instant pot 1 hour
- Natural release 1/2 hour
*** Soup
- Blend 1/3 of the beans
- Garlic
  - 1 min
- Chili powder, cumin, oregano, cayenne
  - 1 min
- Pinto beans, vegetable broth
- Medium-high to boil
  - Simmer on medium
  - 15 mins
* Pakora :indian:snack:
:PROPERTIES:
:source-url: https://www.veganricha.com/onion-fritters-simple-pleasures/
:END:
** Ingredients
*** Vegetables
- 2 medium onions -- sliced thin
- 1 chili pepper -- chopped
- 1 bunch cilantro -- chopped
- pinch hing
- 1 tsp cumin
- 1 tsp ajwain (carom seeds)
- 3 tsp salt
*** Batter
- 3 tbsp besan
- water
** Directions
- Mix vegetables
- Add to batter
- Medium high
  - Fry spoonfuls of batter
  - Turn for even frying
- Fry chilies separately for garnish

* Toor dal :indian:
:PROPERTIES:
:time: fast
:servings: 4
:END:
** Ingredients
*** Dal
- 2 cups toor dal
- 5 cups water
- salt
*** Tempering
- 1/2 tsp mustard/jeera [= cumin] seeds
- 1 large tomato -- chopped
- large pinch hing
- 8 curry leaves
- 2 dried chilies
- 3 cloves garlic
- salt
- sugar
- cayenne pepper
** Directions
*** Dal
- Instant pot 3 minutes, 10 minute release
*** Tempering
- Oil, mustard/jeera seeds, hing
- Chilies, curry leaves
  - Stir a minute
- Garlic
  - 30 seconds
- Chili powder, tomato
- Sugar
  - Until raw tomato smell goes away
- Mix with dal
* Masoor dal tadka :indian:
:PROPERTIES:
:source-url: https://www.veganricha.com/masoor-dal-tadka-indian-red-lentil-dal/
:servings: 2
:time: long
:END:
** Ingredients
*** TODO groceries
- Bay leaves
*** Dal
  - 1 cup masoor dal
  - 3 cups water
  - 1/2 tsp salt
*** Tempering 1
- 1 tsp oil
- 1 medium red onion -- thinly sliced
- 2 cloves garlic -- minced
- 1 tsp ginger -- minced
- 1 tsp coriander -- ground
- 1/2 tsp cumin -- ground
- 1 medium tomato -- chopped
- 1/4 tsp salt
- 1 tablespoon yogurt
*** Tempering 2
  - 2 tsp oil
  - 1/2 tsp cumin -- seeds
  - 2 bay leaves
  - 2 chilies
  - 1/2 tsp kasuri methi
  - 1 garlic clove -- julienned
  - 1/2 inch ginger -- julienned
  - 1/4 tsp paprika
  - pinch ground cloves
  - cliantro, lemon juice -- garnish
** Directions
*** Dal
- Instant pot 3 minutes, 10 minute release
*** Tempering 1
- Medium pan
  - Oil, onion, garlic, salt
  - Until onion is golden-brown
  - Take half for garnish
- Add ginger, coriander, cumin
- Add tomato, 2 tbsp water, 1/4 tsp salt
  - Until tomato is tender
  - Mash large pieces
- Add yogurt
- Mix in dal and boil
*** Tempering 2
- Oil, cumin
  - Until fragrant
- Bay leaves, chilies, kasuri methi, ginger, garlic
  - Until garlic is golden
- Paprika, cloves
  - Take off heat
- Add reserved onion
- Add to dal
- Garnish with cilantro, lemon juice
* Malai Kofta :indian:
:PROPERTIES:
:source-url: https://www.veganricha.com/vegan-malai-kofta-recipe/
:servings: 4
:time: long
:END:
** Ingredients

- 1/4   cup     ( 50   g )   shelled hemp seeds or pumpkin seeds or almond flour or chopped cashews    (cashews and almonds are the most neutral flavor)
- 1   cup     ( 210   g )   heaping cup cubed potato or 1 cup grated/shredded potato, raw   (1 medium potato)
- 2   cloves        garlic
- 15   oz     ( 430   g )    can chickpeas    or 1.5 cups cooked
- 1/2 to 3/4   tsp        salt   depends on if using salted or unsalted chickpeas, I used 3/4 tsp
- 1   tsp        garam masala
- 1/2   tsp        ground cumin   preferably roasted or use Dry toasted whole cumin seeds
- 1/4 to 1/2   tsp        cayenne/indian red chili powder
- 3   Tbsp        oat flour or regular flour   Or other flour of choice
- 1   Tbsp        cornstarch or other starch
- a generous pinch of baking soda
- 2   teaspoons        safflower or other neutral oil
- 1/2   teaspoon        cumin seeds
- 1/2   teaspoon        coriander seeds
- 1        bay leaf
- 8    cloves        garlic   coarsely chopped
- 1   cup     ( 160   g )   chopped red onion
- 1   1-inch knob         of ginger, chopped
- 1/2   teaspoon        turmeric
- 1/4 to 1/2   teaspoon        cayenne
- 1   teaspoon        Garam Masala
- 1 1/2   cups     ( 225   g )   chopped tomato   fresh or canned
- 1/4   cup     ( 30   g )   raw cashews,    See note for nut free
- 1/2 to 1   teaspoon        salt
- 1/2   cup     ( 120   ml )   water or unsweetened almond or other non dairy milk   divided
- 1 1/2   teaspoons     ( 7   g )   dried fenugreek leaves
- 1/2   teaspoon     ( 3   g )   sugar
- Cashew cream or coconut cream for garnish

** Directions

1. Kofta: Process the hemp seeds or nuts until you have a coarse meal. Add potato and process until coarse. Add the rest of the ingredients and pulse until most of the chickpeas have broken down but not a paste. (Without processor, use nut or seed flour and grated potato. Then mash chickpeas and mix)
2. The potato will leak moisture in the mixture in some seconds making it easy to make smooth balls. Do not let the mixture sit for too long at this point. Add more flour or starch if the mixture is too moist. Add a tbsp nutritional yeast for cheesier flavor profile.
3. Take 2 to 3 Tbsp of the mixture and make round or football shaped balls - 1.5 inch size or smaller so they cook through. Place on a parchment lined baking sheet. Bake at 425 F (218 C). For 20 minutes. Or pan fry in 1/2 inch oil for 5 to 6 minutes until golden on most sides.
4. Gravy: Heat the oil in a large skillet over medium heat. Add the cumin, coriander, and bay leaf. Cook for 1 minute. Add the garlic and cook until slightly golden on some edges, 2 minutes. Add the onion and ginger, and cook until golden, 7 minutes, stirring occasionally. Add the turmeric, cayenne, and garam masala, and mix for a few seconds.
5. Add the tomato, cashews, 1/4 cup water and salt and cook until the tomatoes are saucy, 5 to 6 minutes. Stir occasionally to avoid sticking. Cool slightly, then transfer to a blender.
6. Blend the mixture with 1/4 cup water, half the fenugreek leaves and sugar until smooth. Fold in the remaining fenugreek leaves.  (This sauce is incredibly versatile,  you can just add some chickpeas, baked tofu, roasted or par-cooked veggies and simmer and use!)
7. Bring the blended sauce to a boil, add baked kofta balls and serve. Garnish with some cashew cream or other on dairy cream and cilantro. Serve with  Naan  or rice.   To store: store the balls and sauce Separately until ready to serve.

* Soda Bread :bread:
:PROPERTIES:
:source-url: https://www.budgetbytes.com/easy-soda-bread/
:servings: 2
:time: long
:END:
** Ingredients
*** Buttermilk
- 1 cup oat milk
- 1 tbsp vinegar
*** Bread
- 2 cups flour
- 1/2 tsp baking soda
- 1/2 tsp salt
** Directions
*** Buttermilk
- Oat milk and vinegar
- 10 minutes
*** Bread
- Preheat 450
- Flour, baking soda, salt
- Make a well in the middle, buttermilk
- With a fork, slowly mix flour into milk
- Shape dough, put in dutch oven
- Bake:
    - 10 minutes at 450
    - 20 minutes at 400

* Burrito Bowl :mexican:
:PROPERTIES:
:source-url: https://www.budgetbytes.com/poor-mans-burrito-bowls/
:servings: 3
:time: short
:END:
** Ingredients
- 2 cups uncooked rice
- 1/2 tsp salt
- 2 15oz cans black beans
- 1/2 tsp ground cumin
- 1/4 tsp garlic powder
- 1 16oz jar salsa
- 6 oz shredded cheese
- 1 bunch green onions
- 1 jalapeno
** Directions
- Bowl
* Rice Pancakes :breakfast:
:PROPERTIES:
:source-url: https://www.budgetbytes.com/rice-pancakes/
:servings:
:time: short
:END:
** Ingredients
- 1 1/2 cups cooked rice
- 1 egg
- 1/2 tsp vanilla
- 1/2 tsp cinnamon
- 1/4 tsp salt
- 1 Tbsp oil
** Directions
- Rice, egg, vanilla, cinnamon
- Cook on medium

* Vegan Red Beans and Rice :beans:
:PROPERTIES:
:source-url: https://www.budgetbytes.com/vegan-red-beans-rice/
:time: long
:END:
** Ingredients
- 2 Tbsp olive oil
- 1 onion
- 1 bell pepper
- 4 stalks celery
- 4 cloves garlic
- 1 lb dry red beans
- 6 cups vegetable broth
- 1 tsp thyme
- 1 tsp oregano
- 1 bay leaf
- 1/2 Tbsp smoked paprika
- Freshly cracked pepper (about 10-15 cranks of a pepper mill)
- pinch cayenne pepper
- 6 cups cooked rice
- 1 bunch green onions
** Directions

1. The night before, Place your beans in a large pot and fill with enough cool water to cover the beans by a few inches. Place the beans in the refrigerator to soak over night.
2. When you're ready to cook, finely dice the celery, bell pepper, and onion, and mince the garlic. Cook the celery, bell pepper, onion, and garlic in a large pot with the olive oil over medium heat until softened (5-7 minutes).
3. Drain the soaked beans in a colander and rinse with fresh, cool water. Add the rinsed beans to the pot with the vegetables. Also add the vegetable broth, thyme, oregano, bay leaf, smoked paprika, some freshly cracked pepper, and a pinch of cayenne pepper.
4. Place a lid on the pot and bring it up to a full boil over high heat. After it reaches a boil, turn the heat down to low and allow the pot to simmer for at least two hours. Make sure the pot is simmering the entire time, increasing the heat if needed. Stir the pot occasionally to make sure nothing is sticking to the bottom. Keep the lid in place the entire time to keep the beans from drying out.
5. After two hours (or longer if desired) the beans should be soft and tender. Mash some of the beans against the side of the pot with the back of a spoon. This will thicken the pot and make the classic, creamy texture of the dish. Remove the bay leaf and allow the pot to simmer for about 30 minutes more (after smashing) to help it thicken.
6. To serve, add a scoop of red beans to a bowl and top with a scoop warm, cooked rice. Sprinkle sliced green onions over top and add a dash of hot sauce if desired.

* Samosa :indian:snack:
:PROPERTIES:
:source-url: https://www.vegrecipesofindia.com/samosa-recipe-punjabi-samosa/
:servings:
:prep-time:
:cook-time:
:ready-in:
:END:
** Ingredients

- 250 g flour
- 1 tsp ajwain seeds [= carom]
- 1 tsp salt
- 6 Tbsp oil
- 7 Tbsp water
- 3 medium potatoes ~300 g
- 1/2 c peas
- 2 cups water –- for steaming
- 1 Tbsp oil
- 1/2 tsp cumin seeds
- 1 tsp ginger
- 1 chili
- ▢ ½ teaspoon red chili powder or cayenne pepper
- ▢ 1 pinch asafoetida (hing) – optional
- ▢ 1 to 2 teaspoons dry mango powder (amchur)
- ▢ salt as required
- ▢ 1 tablespoon coriander leaves (cilantro), chopped
- ▢ oil for deep frying – as required, any neutral flavored oil
- ▢ ½ inch cinnamon
- ▢ 1 clove – optional
- ▢ 3 black peppercorns
- ▢ 1 green cardamom
- ▢ ½ teaspoon cumin seeds
- ▢ ½ teaspoon fennel seeds
- ▢ 2 teaspoons coriander seeds
** Directions

1. Take the flour, carom seeds, salt in a bowl. Mix well and add ghee.
2. With your fingertips rub the ghee or oil in the flour to get a breadcrumb like consistency.
3. The whole mixture should clump together when joined and not fall apart.
4. Add water in parts and knead to a firm dough.
5. If the dough looks dry or floury, then add 1 to 2 tablespoons more water and knead.
6. Cover the dough with a moistened napkin and set aside for 30 minutes.
7. Steam or boil the potatoes and peas till are cooked completely. Drain them of any extra water in a colander or sieve.
8. Peel the boiled potatoes and chop them into small cubes
9. Dry roast all the whole spices mentioned in the above list until fragrant taking care not to burn them.
10. When the spices are warm or cool at room temperature, grind them in a dry grinder or coffee grinder to a semi-fine or fine powder.
11. Heat oil in a pan. add the cumin seeds and crackle them.
12. Add the ginger and green chillies. Sauté for a few seconds until the raw aroma of ginger goes away.
13. Add the steamed green peas, red chili powder, the freshly ground spice powder, dry mango powder and asafoetida.
14. Stir and sauté on a low heat for 1 to 2 minutes.
15. Add the potato cubes. Mix very well and sauté for about 2 to 3 minutes on low heat with frequent stirring.
16. Set aside the potato filling aside to cool at room temperature.
17. After resting the dough for 30 minutes, divide the dough in 6 equal pieces.
18. Take each piece and roll in your palms first to make a smooth ball.
19. Then roll it with a rolling pin keeping the thickness to 1 mm throughout.
20. Cut with a knife or a pastry cutter through the center of the rolled samosa pastry.
21. With a brush or with your finger tips, spread some water all over the edges.
22. Join the two straight ends forming a cone shape.
23. Press the edges so that they get sealed well.
24. Stuff the prepared samosa cone with the prepared potato-peas stuffing.
25. Pinch a part on the edge (check the video & photos). This helps the samosa to stand once it is shaped.
26. Press both the edges. Be sure there are no cracks.
27. Prepare all the samosa this way and keep covered with a moist kitchen napkin.
28. Now heat oil for deep frying in a kadai or pan. Once the oil becomes hot (test by adding a small piece of dough – it should come up quickly once added to the hot oil).   Gently slide the prepared stuffed samosa & quickly reduce the flame to low.
29. Turn over in between and fry until golden. Drain the fried samosa on paper towels to remove excess oil.
30. Fry them in batches. For frying the second batch, again increase the temperature of the oil to medium-heat. Do not overcrowd the pan while frying.
31. Add the samosa and then lower the flame, thereby decreasing the temperature of oil.
32. This way fry all the samosa in batches.
33. Serve samosa hot or warm with coriander chutney, tamarind chutney or tomato ketchup.
34. They can also be served with a yogurt dip or plain raita. Another way is to serve it with  chana masala (chickpea curry).
35. We usually pair samosa with masala chai or ginger chai.
36. Even bread or pav (Indian bread rolls) can be served with it.
37. Whatever you serve samosa with, remember to have hot masala chai with it.
