#+title: Mizuho

* Vocab
金融 -- キンユウ -- Finance
システム障害 -- System failure
* System failures
:LINKS:
10 system failures -- https://medium.com/tokyo-fintech/the-chronicles-of-mizuhos-system-failures-dbc11c58a99b
:end:
** 2021-02-28 -- Broken ATMs -- Eating cash cards

** 2023-03-07 -- Failed ATMS

** 2023-03-12 -- Late wire transfers
:LINKS:
https://business.nikkei.com/atcl/gen/19/00139/031600020/
:end:


** 2022-01-11 -- Online banking services
:LINKS:
https://english.kyodonews.net/news/2022/01/123013fe133c-mizuho-hit-by-issues-with-online-business-banking-services.html
:end:

* Response

** Financial Services Agency
*** 2021-09-22 -- Administrative actions I
:LINKS:
https://www.fsa.go.jp/en/news/2021/20210922.html
https://english.kyodonews.net/news/2021/09/eead25ed2bd4-japan-regulators-to-oversee-computer-system-failures-at-mizuho.html
https://asia.nikkei.com/Business/Finance/Mizuho-s-crash-hit-4bn-system-to-go-under-unprecedented-state-oversight
:end:

*** 2021-12-15 -- Administrative actions II
:LINKS:
https://www.fsa.go.jp/en/news/2021/20211126.html
https://www.reuters.com/markets/asia/japan-regulator-reprimand-mizuho-again-ceo-resign-nikkei-2021-11-18/
:end:
**** Direct Causes
Direct causes of the series of the recent system failures are found as follows:
    The Bank has failed to conduct verification sufficiently for ensuring quality in system development and responses to failures.

    The Bank has not developed a maintenance and operation structure to ensure stable operation of its new core system (hereinafter "MINORI"), such as failing to correct problems in system maintenance and operation and to govern outsourcees sufficiently.

    The Bank has failed to verify its preparedness for emergencies sufficiently through drills and training.
****
** Resignations
:LINKS:
https://www.reuters.com/markets/asia/japan-regulator-reprimand-mizuho-again-ceo-resign-nikkei-2021-11-18/
https://www.reuters.com/business/finance/japans-finance-ministry-takes-punitive-action-vs-mizuho-over-forex-law-2021-11-26/
https://www.bankingdive.com/news/mizuho-group-ceo-resigns-amid-spate-of-it-woes/610633/
:end:

** Postmortem
:LINKS:
https://www.mizuhogroup.com/binaries/content/assets/pdf/mizuhoglobal/investors/financial-information/ir-information/briefing/202111_system.pdf
https://www.mizuho-fg.co.jp/release/20210405_2release_jp.html
https://www.jstage.jst.go.jp/article/jsimconf/81/0/81_137/_pdf/-char/ja
https://www.inf.shizuoka.ac.jp/labs/behavior_detail.html?UC=endo-m
:end:

* Other thoughts
** Southwest airlines failures
:LINKS:
https://www.reuters.com/business/aerospace-defense/southwest-network-failure-raises-concerns-over-systems-strength-2023-04-19/
:end:

Good comparison?
** Old systems
:LINKS:
https://twitter.com/JDMayger/status/1618600586529894400
:end:

Is this why companies never update old systems?
